---
#Miner
target_miner_tag: "gateway-latest"
seed_node: "/ip4/199.229.250.69/tcp/2154"
seed_peer: "/p2p/11hVUgp5hMrZhCKcbamRUL1RnDxbEdpDVytSZsiGSkjRJxbujwa"

target_miner_key: True # use ECC key
target_pf_concentrator_interface: "spi" # or usb
target_pf_concentrator_model: "sx1250" # only sx1250 for now

#Packet Forwarder
target_pf_image: "ghcr.io/petrkr/sx1302_hal"
target_pf_tag: "0.0.14"
