---
- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: restart helium-packet-forwarder
  systemd:
    name: helium-packet-forwarder
    state: restarted

- name: restart helium-miner
  systemd:
    name: helium-miner
    state: restarted
